#Test configuration
---
org:
   name: qa
   admin: admin
   password: changeit
   bucket: test-data
influx2:
   url: http://localhost:9999
   api: /api/v2
   build: nightly
telegraf:
   confPath: etc/conf.toml
   confDownload: DEFAULT
   name: test-telegraf
